services:
  jaeger:
    container_name: sainapsis-bridge-jaeger
    image: jaegertracing/all-in-one:latest
    command:
      - "--collector.otlp.http.cors.allowed-origins=http://localhost:3000"
      - "--collector.otlp.http.cors.allowed-headers=*"
      - "--collector.otlp.http.tls.enabled=false"
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - QUERY_BASE_PATH=/
    networks:
      - jaeger-network
    restart: no

networks:
  jaeger-network:
    driver: bridge
